spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/bike_shop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: never

bikeShop:
  remember.me.key: ${REMEMBER_ME_KEY:secret}

mail:
  bikeshop: "bikeshop@bikes.com"
  host: localhost
  port: 1025
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}